spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/capricorn?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5